#!/usr/bin/env bash

DIR="$(cd "$(dirname "$0")/.." && pwd)"
TMPDIR=$(mktemp -d)
CURRENT_BRANCH=$(git branch --show-current)
GITBRANCH=gh-pages

run_git_command() {
  echo "$*"
  eval "$*"
}

clean_exit() {
  [[ -d "$TMPDIR" ]] && rm -rf "$TMPDIR"
  exit
}

if [[ $CURRENT_BRANCH -eq main ]]; then
  if [[ -z $(git status public | grep 'nothing to commit') ]]; then
    run_git_command 'git add public'
    run_git_command 'git commit -m "Update static files in public"'
    run_git_command "git push origin $CURRENT_BRANCH"
    run_git_command 'git fetch -a'

    grep -q $GITBRANCH <(git branch -a) && run_git_command "git push -d origin $GITBRANCH"
    grep -q $GITBRANCH <(git branch -a) && run_git_command "git branch -d $GITBRANCH"

    cd "$TMPDIR" || clean_exit
    run_git_command 'git init'

    for i in config HEAD; do
      cat "$DIR"/.git/$i | sed "s,$CURRENT_BRANCH,$GITBRANCH,g" >"$TMPDIR"/.git/$i
    done

    cp -r "$DIR"/public/* "$TMPDIR"/

    run_git_command 'git add .'
    run_git_command "git commit -m 'Publish $GITBRANCH'"
    run_git_command "git push origin $GITBRANCH"
  else
    echo "No changes have been made"
  fi
fi

clean_exit
