name: Build

on:
  workflow_dispatch:
    inputs:
      build:
        required: true
        default: "markdown"
        type: choice
        options:
          - markdown
          - json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - name: Checkout data branch
        uses: actions/checkout@v3
        with:
          ref: data
          path: data

      - name: Build content
        if: ${{ inputs.build == 'markdown' }}
        run: |
          ./main/scripts/build-content.sh -o ./data/content

      - name: Build json
        if: ${{ inputs.build == 'json' }}
        run: |
          ./main/scripts/json-markdown-parser.sh -w ./data/data.json -c ./data/content

      - name: Commit and push
        working-directory: ./data
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git config push.default current
          git pull
          git add .
          git commit -m "generated"
          git push
